export const DEFAULT_TABLE_PAGE_SIZE = 10;
export const DEFAULT_TABLE_PAGE_SIZE_IN_DESKTOP_VIEW = 25;
export const DEFAULT_NUMBER_OF_PLAYERS_TO_COMPARE = 2;
export const MAXIMUM_NUMBER_OF_PLAYERS_TO_COMPARE = 4;
